brahma/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('area-do-leo/', views.areaDoLeo, name='areaDoLeo'),
    path('cadastrar-pessoa-fisica/', views.cadastrarPessoaFisica, 
        name='cadastrarPessoaFisica'),
    path('cadastrar-pessoa-juridica/', views.cadastrarPessoaJuridica, 
        name='cadastrarPessoaJuridica'),
    path('cadastrar-equipamento/', views.cadastrarEquipamento, 
        name='cadastrarEquipamento'),
    path('cadastrar-item/', views.cadastrarItem, 
        name='cadastrarItem'),
    path('cadastrar-ordem-servico/', views.cadastrarOrdemServico, 
        name='cadastrarOrdemServico'),
    path('consultar-clientes/', views.consultarClientes, 
        name='consultarClientes'),
]

core/models.py
from django.db import models

class PessoaFisica(models.Model):
    nome = models.CharField(max_length=100)
    celular = models.CharField(max_length=12)
    data_instalacao = models.DateField()

    def __str__(self):
        return self.nome

class PessoaJuridica(models.Model):
    razao_social = models.CharField(max_length=100, unique=True)
    nome_fantasia = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=100, unique=True)
    celular = models.CharField(max_length=12)
    nome_contato = models.CharField(max_length=50)
    data_instalacao = models.DateField()

    def __str__(self):
        return self.nome_fantasia

class Equipamento(models.Model):
    OCUPADO = 'OC'
    DISPONIVEL = 'DI'
    DEFEITO = 'DE'

    STATUS_EQUIPAMENTOS = ( 
        (DISPONIVEL, 'Disponivel'),
        (OCUPADO, 'Ocupado'),
        (DEFEITO, 'Defeito'),
    )

    nome = models.CharField(max_length=100, unique=True)
    status = models.CharField(max_length=2, choices=STATUS_EQUIPAMENTOS, default=DISPONIVEL)

    def __str__(self):
        return self.nome

class Item(models.Model):
    descricao = models.CharField(max_length=100)
    qtd_estoque = models.PositiveIntegerField()
    def __str__(self):
        return self.descricao

class OrdemServico(models.Model):
    pessoa_fisica = models.ForeignKey(PessoaFisica, 
        on_delete=models.CASCADE, null=True, blank=True)
    pessoa_juridica = models.ForeignKey(PessoaJuridica, 
        on_delete=models.CASCADE, null=True, blank=True)
    dia = models.DateField()
    descricao = models.CharField(max_length=1000, null=True, blank=True)
    equipamento = models.ManyToManyField(Equipamento)
    itens = models.ManyToManyField(Item, blank=True)
    assepsia = models.BooleanField()

    

core/forms.py
from django import forms

from .models import (
    PessoaFisica, 
    PessoaJuridica,
    Equipamento,
    Item,
    OrdemServico
)

class CadastrarPessoaFisicaForm(forms.ModelForm):
    class Meta:
        model = PessoaFisica

        fields = [
            'nome',
            'celular',
            'data_instalacao'
        ]

    def __init__(self, *args, **kwargs):
        super(CadastrarPessoaFisicaForm, self).__init__(*args, **kwargs)
        self.fields['nome'].label = "Nome do cliente"
        self.fields['celular'].label = "Celular do cliente"
        self.fields['data_instalacao'].label = "Data de Instalação"
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CadastrarPessoaJuridicaForm(forms.ModelForm):
    class Meta:
        model = PessoaJuridica

        fields = [
            'razao_social',
            'nome_fantasia',
            'cnpj',
            'celular',
            'nome_contato',
            'data_instalacao', 
        ]

    def __init__(self, *args, **kwargs):
        super(CadastrarPessoaJuridicaForm, self).__init__(*args, **kwargs)
        self.fields['razao_social'].label = 'Razão Social'
        self.fields['nome_fantasia'].label = 'Nome Fantasia'
        self.fields['cnpj'].label = 'CNPJ'
        self.fields['celular'].label = 'Número de Celular'
        self.fields['nome_contato'].label = 'Nome do Contato'
        self.fields['data_instalacao'].label = 'Data de Instalação'
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CadastrarEquipamentoForm(forms.ModelForm):
    class Meta:
        model =  Equipamento
        fields = [
            'nome',
            'status'
        ]

    def __init__(self, *args, **kwargs):
        super(CadastrarEquipamentoForm, self).__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome do equipamento'
        self.fields['status'].label = 'Status do Equipamento'
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CadastrarItemForm(forms.ModelForm):
    class Meta:
        model =  Item
        fields = [
            'descricao',
            'qtd_estoque'
        ]

    def __init__(self, *args, **kwargs):
        super(CadastrarItemForm, self).__init__(*args, **kwargs)
        self.fields['descricao'].label = 'Nome do Item'
        self.fields['qtd_estoque'].label = 'Quantidade em estoque'

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CadastrarOrdemServicoForm(forms.ModelForm):
    class Meta:
        model =  OrdemServico
        fields = [
            'pessoa_fisica',
            'pessoa_juridica',
            'dia',
            'descricao',
            'equipamento',
            'itens',
            'assepsia',
        ]

        widgets = {
			'equipamento': forms.CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        super(CadastrarOrdemServicoForm, self).__init__(*args, **kwargs)
        self.fields['equipamento'].queryset = Equipamento.objects.filter(
            status = 'DI')
        self.fields['descricao'].label = 'Descrição do que foi feito'
        self.fields['dia'].label = 'Dia que foi executado o serviço'
        self.fields['itens'].label = 'Itens que foram deixados'
        self.fields['assepsia'].label = 'Assepsia foi feita?'

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

core/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse


from .forms import (
    CadastrarPessoaFisicaForm, 
    CadastrarPessoaJuridicaForm,
    CadastrarEquipamentoForm,
    CadastrarItemForm,
    CadastrarOrdemServicoForm,
)

from .models import (
    PessoaJuridica,
    PessoaFisica,
    Equipamento,
    Item,
    OrdemServico
)

def index(request):
    return render(request, 'core/index.html')

def areaDoLeo(request):
    return render(request, 'core/area_do_leo.html')

def cadastrarPessoaFisica(request):
    form = CadastrarPessoaFisicaForm(request.POST or None, 
        request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)

    return render(request, 'core/cadastrar_pessoa_fisica.html', {'form':form})

def cadastrarPessoaJuridica(request):
    form = CadastrarPessoaJuridicaForm(request.POST or None, 
        request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)

    return render(request, 'core/cadastrar_pessoa_juridica.html', {'form':form})

def cadastrarEquipamento(request):
    equipamentos = Equipamento.objects.all()

    form = CadastrarEquipamentoForm(request.POST or None, 
        request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)

    return render(request, 'core/cadastrar_equipamento.html', 
        {'form':form, 'equipamentos':equipamentos})

def cadastrarItem(request):
    form = CadastrarItemForm(request.POST or None, 
        request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)

    return render(request, 'core/cadastrar_item.html', {'form':form})

def cadastrarOrdemServico(request):
    form = CadastrarOrdemServicoForm(request.POST or None, 
        request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            data = form.clean()
            for equipamento in data['equipamento']:
                equipamento.status = 'OC'
                equipamento.save()
            form.save()
            return HttpResponseRedirect(request.path_info)

    return render(request, 'core/cadastrar_ordem_servico.html', {'form':form})

def consultarClientes(request):
    clientes_pessoa_fisica = PessoaFisica.objects.all()
    clientes_pessoa_juridica = PessoaJuridica.objects.all()

    context = {
        'clientes_pessoa_fisica':clientes_pessoa_fisica,
        'clientes_pessoa_juridica':clientes_pessoa_juridica,
    }

    return render(request, 'core/consultar_clientes.html', context)

core/templates/core/area_do_leo.html
{% extends 'base.html' %}

{% block main %}
    <div class="lista_links">
        <ul>
            <a href="{% url 'core:cadastrarPessoaFisica' %}"><li>Cadastrar Pessoa Física</li></a>
            <a href="{% url 'core:cadastrarPessoaJuridica' %}"><li>Cadastrar Pessoa Jurídica</li></a>
            <a href="{% url 'core:cadastrarEquipamento' %}"><li>Cadastrar equipamento</li></a>
            <a href="{% url 'core:cadastrarItem' %}"><li>Cadastrar item</li></a>
            <a href="{% url 'core:cadastrarOrdemServico' %}"><li>Ordem de Serviço</li></a>
            <a href="{% url 'core:consultarClientes' %}"><li>Consultar Clientes</li></a>
        </ul>
    </div>
{% endblock%}

core/templates/core/cadastrar_equipamento.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form action="" method="post" class="formulario form-group">
        {% csrf_token %}
        
        <h1>Cadastro de equipamento para uso</h1>

        <div class="form-group">
            {{ form.nome | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.status| as_crispy_field }}
        </div>
        
        <button type="submit" class="btn botao_submissao mt-4">Salvar</button>

        <button type="button" class="btn mt-5" data-toggle="collapse" data-target="#equipamentos_salvos">Mostrar Equipamentos salvos</button>

        <div class="collapse" id="equipamentos_salvos">
            <table border=1 class="table table-dark mt-5">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Equipamento</th>
                        <th scope="col">Status do Equipamento</th>
                    </tr>
                </thead>
                <tbody>
                    {% for equipamento in equipamentos %}
                        <tr>
                            <th scope="row">#</th>
                            <td>{{ equipamento.nome }}</td>
                            {% if equipamento.status == 'DI'%}
                                <td>Disponível</td>
                            {% elif equipamento.status == 'OC'%}
                                <td>Ocupado</td>
                            {% else %}
                                <td>Defeito</td>
                            {% endif %}
            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

{% endblock %}

core/templates/core/cadastrar_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form action="" method="post" class="formulario form-group">
        {% csrf_token %}
        
        <h1>Cadastro de itens e produtos</h1>

        <div class="form-group">
            {{ form.descricao | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.qtd_estoque | as_crispy_field }}
        </div>
        
        <button type="submit" class="btn botao_submissao mt-4">Salvar</button>
    </form>
{% endblock %}

core/templates/core/cadastrar_ordem_servico.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form action="" method="post" class="formulario form-group">
        {% csrf_token %}
        
        <h1>Cadastro de Ordem de Serviço</h1>

        <button type="button" class="btn mt-3" onclick="ativarInputPessoaFisica()">Pessoa Fisica</button>
        <button type="button" class="btn mt-3 mb-3" onclick="ativarInputPessoaJuridica()">Pessoa Juridica</button>

        <div class="form-group" id="input-pessoa-fisica">
            {{ form.pessoa_fisica | as_crispy_field }}
            {{ form.pessoa_fisica.errors }}
        </div>

        <div class="form-group" id="input-pessoa-juridica">
            {{ form.pessoa_juridica | as_crispy_field }}
            {{ form.pessoa_juridica.errors }}
        </div>

        <div class="form-group">
            {{ form.dia | as_crispy_field }}
        </div>

        <div class="form-group">
            {{ form.descricao | as_crispy_field }}
            {{ form.descricao.errors }}
        </div>

        <div class="form-group">
            <small>Equipamentos</small>
            
            {% for value, text in form.equipamento.field.choices %}
                <div style="display: flex; justify-content: flex-start;">
                    <input type="checkbox" name="equipamento" id="id_equipamento_{{value}}" value="{{value}}" class="form-control">
                    <div>{{ text }}</div>
                </div>
            {% endfor %}
            
        </div>

        <div class="form-group">
            {{ form.itens | as_crispy_field }}
        </div>

        <div class="assepsia">
            {{ form.assepsia | as_crispy_field }}
        </div>
        
        <button type="submit" class="btn botao_submissao mt-4">Salvar</button>
    </form>
{% endblock %}

core/templates/core/cadastrar_pessoa_fisica.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form action="" method="post" class="formulario form-group">
        {% csrf_token %}
        
        <h1>Cadastro de pessoa física (delivery)</h1>

        <div class="form-group">
            {{ form.nome | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.celular | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.data_instalacao | as_crispy_field }}
        </div>
        
        <button type="submit" class="btn botao_submissao mt-4">Salvar</button>
    </form>
{% endblock %}

core/templates/core/cadastrar_pessoa_juridica.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    
    <form action="" method="post" class="formulario form-group">
        {% csrf_token %}
        
        <h1>Cadastro de pessoa jurídica (bar e restaurante)</h1>

        <div class="form-group">
            {{ form.razao_social | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.nome_fantasia | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.cnpj | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.celular | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.nome_contato | as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.data_instalacao | as_crispy_field }}
        </div>
        
        <button type="submit" class="btn mt-4 botao_submissao">Salvar</button>
    </form>
{% endblock %}

core/templates/core/consultar_clientes.html
{% extends 'base.html' %}

{% block main %}

<div class="ml-5 mr-5">
    <table border=1 class="table table-dark mt-5">
        <caption>Pessoas Física</caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Celular</th>
                <th scope="col">Data de instalação</th>
                <th scope="col">Equipamentos com cliente</th>
            </tr>
        </thead>
        <tbody>
            {% for pessoa_fisica in clientes_pessoa_fisica %}
                <tr>
                    <th scope="row">#</th>
                    <td><a href="">{{ pessoa_fisica.nome }}</a></td>
                    <td>{{ pessoa_fisica.celular}}</td>
                    <td>{{ pessoa_fisica.data_instalacao }}</td>
                    <td>
                        {% for ordem_servico in pessoa_fisica.ordemservico_set.all %}
                            {% for equipamento in ordem_servico.equipamento.all %}
                                {{ equipamento.nome }}
                                <br>
                            {% endfor %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <table border=1 class="table table-dark mt-5">
        <caption>Pessoas Jurídica</caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Razão Social</th>
                <th scope="col">Nome Fantasia</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Celular</th>
                <th scope="col">Nome do Contato</th>
                <th scope="col">Data da Instalação</th>
            </tr>
        </thead>
        <tbody>
            {% for pessoa_juridica in clientes_pessoa_juridica %}
                <tr>
                    <th scope="row">#</th>
                    <td><a href="">{{ pessoa_juridica.razao_social }}</a></td>
                    <td>{{ pessoa_juridica.nome_fantasia }}</td>
                    <td>{{ pessoa_juridica.cnpj }}</td>
                    <td>{{ pessoa_juridica.celular }}</td>
                    <td>{{ pessoa_juridica.nome_contato }}</td>
                    <td>{{ pessoa_juridica.data_instalacao }}</td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'base.html' %}

{% block main %}

{% endblock %}