brahma/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('area-do-leo/', views.areaDoLeo, name='areaDoLeo'),
    path('cadastrar-pessoa-fisica/', views.cadastrarPessoaFisica, 
        name='cadastrarPessoaFisica'),
    path('cadastrar-pessoa-juridica/', views.cadastrarPessoaJuridica, 
        name='cadastrarPessoaJuridica'),
    path('cadastrar-equipamento/', views.cadastrarEquipamento, 
        name='cadastrarEquipamento'),
    path('cadastrar-item/', views.cadastrarItem, 
        name='cadastrarItem'),
    path('cadastrar-ordem-servico/', views.cadastrarOrdemServico, 
        name='cadastrarOrdemServico'),
    path('consultar-clientes/', views.consultarClientes, 
        name='consultarClientes'),
]

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="{% static 'core/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <script src="{% static 'core/js/main.js' %}"></script>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'core:areaDoLeo' %}">Área do Leo</a></li>
        </ul>
    </nav>
    {% block main %}
    {% endblock %}
</body>
</html>